# Generated by Django 2.1.2 on 2019-09-24 22:19

from django.db import migrations


def create_users_from_passengers(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("fleet_management", "User")
    Passenger = apps.get_model("fleet_management", "Passenger")
    Drive = apps.get_model("fleet_management", "Drive")

    passenger_group = Group.objects.get(name="Passenger")

    for passenger in Passenger.objects.all():
        user = User.objects.create_user(
            username=passenger.email,
            email=passenger.email,
            is_superuser=False,
            is_staff=False,
            country=passenger.country,
            is_active=True,
            first_name=passenger.first_name,
            last_name=passenger.last_name
        )

        user.save()

        passenger_group.user_set.add(user)

        for drive in Drive.objects.filter(passengers=passenger.id):
            drive.passenger = user
            drive.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0016_auto_20190825_2051'),
    ]

    operations = [
        migrations.RunPython(create_users_from_passengers),
    ]
