# Generated by Django 2.1.2 on 2019-09-24 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0017_create_users_from_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='passengers',
        ),
        migrations.AddField(
            model_name='drive',
            name='passenger',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='drives_taken', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drive',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives_driven', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
